name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - name: Build frontend
        run: |
          npm run build
        working-directory: ${{ env.FRONTEND_PACKAGE_NAME }}
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FRONTEND_PACKAGE_NAME }}-build
          path: ${{ env.FRONTEND_PACKAGE_NAME }}/out

  build-wheel:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v6

      - name: Download frontend build
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.PACKAGE_NAME }}-frontend-build
          path: static

      - uses: ./.github/actions/build/build-wheel
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/build/build-wheel@main
        if: github.event.repository.name != 'template-python'

  verify-structure:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/verify-structure
        if: github.event.repository.name == 'template-python'
        with:
          expected-directories: |
            static
            rag_data
          expected-files: |
            static/index.html
            rag_data/tools.json
      - uses: javidahmed64592/template-python/.github/actions/build/verify-structure@main
        if: github.event.repository.name != 'template-python'
