name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-pyproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/validate-pyproject
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/validate-pyproject@main
        if: ${{ github.event.repository.name != 'template-python' }}

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-python-dev
      - name: Check with ruff
        run: |
          uv run -m ruff check

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/mypy
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/mypy@main
        if: ${{ github.event.repository.name != 'template-python' }}

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/pytest
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/pytest@main
        if: ${{ github.event.repository.name != 'template-python' }}

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/bandit
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/bandit@main
        if: ${{ github.event.repository.name != 'template-python' }}

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/pip-audit
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/pip-audit@main
        if: ${{ github.event.repository.name != 'template-python' }}

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci/version-check
        if: ${{ github.event.repository.name == 'template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/ci/version-check@main
        if: ${{ github.event.repository.name != 'template-python' }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - name: Run type checking
        run: |
          npm run type-check
        working-directory: ${{ env.FRONTEND_PACKAGE_NAME }}
      - name: Run linting
        run: |
          npm run lint
        working-directory: ${{ env.FRONTEND_PACKAGE_NAME }}
      - name: Run formatting check
        run: |
          npm run format
        working-directory: ${{ env.FRONTEND_PACKAGE_NAME }}
      - name: Run tests
        run: |
          npm run test:coverage
        working-directory: ${{ env.FRONTEND_PACKAGE_NAME }}
      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: ${{ env.FRONTEND_PACKAGE_NAME }}/coverage
